name: CI
on:
  - push
  - pull_request

jobs:
  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: ${{ matrix.os }} - Atom ${{ matrix.atom_channel }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        atom_channel: [stable] # beta
    steps:
      - uses: actions/checkout@v2
      - uses: UziTech/action-setup-atom@v1
        with:
          channel: ${{ matrix.atom_channel }}
      - name: Versions
        run: |
          apm -v
      - name: Install APM dependencies
        run: |
          apm ci  # uses locked module. use `apm install` for non-locked
      - name: Run tests 👩🏾‍💻
        run: npm run test

  Lint:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - name: Install NPM dependencies
        run: |
          npm ci  # uses locked module. use `npm install` for non-locked
      - name: Lint ✨
        run: npm run lint

  Skip:
    if: contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI 🚫
        run: echo skip ci
